//! Warden anticheat — the client half of the `SMSG_WARDEN_DATA` / `CMSG_WARDEN_DATA` exchange.
//!
//! **Scope, stated up front because it bounds what this can ever do.** A Warden scan set is chosen
//! server-side per session and its checks are typed (`WardenScan.hpp`'s `WindowsScanType`). Of those
//! types, the ones this client can answer are the ones it can *witness about itself*:
//! `HASH_CLIENT_FILE` (it holds the real game files) and `GET_LUA_VARIABLE` (it holds a real Lua VM).
//! `READ_MEMORY`, `FIND_CODE_BY_HASH` and `FIND_MEM_IMAGE_CODE_BY_HASH` ask for bytes at addresses
//! inside `WoW.exe`; benilla is a from-scratch client and has no such image, so it cannot answer them
//! — and answering them from a copy of that binary would mean the check no longer says anything about
//! the client that is actually running. A server that wants to admit this client therefore needs a
//! scan profile made of the witnessable types; `WardenScanMgr::GetRandomScans` already selects by the
//! session's build flag, so that is a database question, not a protocol one.
//!
//! **The crypto is ported from the server it has to interoperate with**, not from memory:
//! `SHA1Randx` is a line-for-line port of tortoise-wow
//! `src/game/Anticheat/Warden/WardenKeyGeneration.h`, and the key direction is read off
//! `Warden.cpp`: the server inits `_inputCrypto` with the FIRST 16 generated bytes and decrypts
//! client→server traffic with it (`DecryptData`, `Warden.cpp:316-319`), and inits `_outputCrypto`
//! with the SECOND 16 for server→client (`EncryptData`, `:321-324`). Mirrored here, so this client
//! encrypts with key #1 and decrypts with key #2. Getting that pair backwards is the failure mode
//! this comment exists to prevent: it does not error, it just yields plausible-looking garbage.
//!
//! There is a second keying step: once a module is loaded the server re-inits both ciphers from the
//! module's own `clientKey`/`serverKey` (`Warden.cpp:141-142`). [`WardenCrypto::rekey`] is that step.

use sha1::{Digest, Sha1};

/// `SHA1Randx` — the server's key-stream generator over the session key
/// (`WardenKeyGeneration.h`). Hash the first half into `o1` and the second into `o2`, then emit
/// 20-byte blocks of `SHA1(o1 ‖ o0 ‖ o2)`, feeding each block back in as the next `o0`.
struct Sha1Randx {
    o0: [u8; 20],
    o1: [u8; 20],
    o2: [u8; 20],
    taken: usize,
}

impl Sha1Randx {
    fn new(seed: &[u8]) -> Self {
        let half = seed.len() / 2;
        let o1: [u8; 20] = Sha1::digest(&seed[..half]).into();
        let o2: [u8; 20] = Sha1::digest(&seed[half..]).into();
        let mut s = Sha1Randx {
            o0: [0u8; 20],
            o1,
            o2,
            taken: 0,
        };
        s.fill_up();
        s
    }

    fn fill_up(&mut self) {
        let mut sha = Sha1::new();
        sha.update(self.o1);
        sha.update(self.o0);
        sha.update(self.o2);
        self.o0 = sha.finalize().into();
        self.taken = 0;
    }

    /// The server's `Generate`: refill only when the current block is spent, then take one byte.
    fn generate(&mut self, out: &mut [u8]) {
        for byte in out.iter_mut() {
            if self.taken == 20 {
                self.fill_up();
            }
            *byte = self.o0[self.taken];
            self.taken += 1;
        }
    }
}

/// RC4/ARC4 — the stream cipher both Warden directions run on (`Auth/ARC4`). Stateful: each call
/// continues the keystream, so one instance belongs to exactly one direction of one session.
pub struct Rc4 {
    s: [u8; 256],
    i: u8,
    j: u8,
}

impl Rc4 {
    pub fn new(key: &[u8]) -> Self {
        let mut s = [0u8; 256];
        for (i, v) in s.iter_mut().enumerate() {
            *v = i as u8;
        }
        let mut j = 0u8;
        for i in 0..256 {
            j = j
                .wrapping_add(s[i])
                .wrapping_add(key[i % key.len()]);
            s.swap(i, j as usize);
        }
        Rc4 { s, i: 0, j: 0 }
    }

    /// XOR `buf` with the next keystream bytes, in place. RC4 is symmetric — the same call both
    /// encrypts and decrypts.
    pub fn apply(&mut self, buf: &mut [u8]) {
        for byte in buf.iter_mut() {
            self.i = self.i.wrapping_add(1);
            self.j = self.j.wrapping_add(self.s[self.i as usize]);
            self.s.swap(self.i as usize, self.j as usize);
            let k = self.s[self.i as usize].wrapping_add(self.s[self.j as usize]);
            *byte ^= self.s[k as usize];
        }
    }
}

/// The bytes generated per direction (`Warden::Warden`'s `KeyLength`).
const KEY_LENGTH: usize = 16;

/// Both directions of one Warden session.
pub struct WardenCrypto {
    /// Applied to what we SEND — the server decrypts it with its `_inputCrypto`.
    outgoing: Rc4,
    /// Applied to what we RECEIVE — the server encrypted it with its `_outputCrypto`.
    incoming: Rc4,
}

impl WardenCrypto {
    /// Derive both ciphers from the SRP6 session key, exactly as `Warden::Warden` does.
    pub fn from_session_key(session_key: &[u8]) -> Self {
        let mut rand = Sha1Randx::new(session_key);
        let mut first = [0u8; KEY_LENGTH];
        let mut second = [0u8; KEY_LENGTH];
        rand.generate(&mut first);
        rand.generate(&mut second);
        WardenCrypto {
            outgoing: Rc4::new(&first),
            incoming: Rc4::new(&second),
        }
    }

    /// Re-key from a loaded module's own pair (`Warden.cpp:141-142`). `client_key` is the one the
    /// server will decrypt our traffic with, so it is ours to encrypt with.
    pub fn rekey(&mut self, client_key: &[u8], server_key: &[u8]) {
        self.outgoing = Rc4::new(client_key);
        self.incoming = Rc4::new(server_key);
    }

    pub fn decrypt(&mut self, buf: &mut [u8]) {
        self.incoming.apply(buf);
    }

    pub fn encrypt(&mut self, buf: &mut [u8]) {
        self.outgoing.apply(buf);
    }
}

/// Server→client Warden opcodes — the first byte of a decrypted `SMSG_WARDEN_DATA` body.
///
/// Their numbering is the oracle for whether [`WardenCrypto`] is keyed correctly: a correct decrypt
/// puts a value in `0..=4` here, a swapped key pair puts noise. That is the check to run first
/// against a live server, since no fixture can stand in for the server's own keystream.
pub mod server_op {
    pub const MODULE_USE: u8 = 0x00;
    pub const MODULE_CACHE: u8 = 0x01;
    pub const CHEAT_CHECKS_REQUEST: u8 = 0x02;
    pub const MODULE_INITIALIZE: u8 = 0x03;
    pub const MEM_CHECKS_REQUEST: u8 = 0x04;
    pub const HASH_REQUEST: u8 = 0x05;
}

/// Client→server Warden opcodes — the first byte of a `CMSG_WARDEN_DATA` body we send.
pub mod client_op {
    pub const MODULE_MISSING: u8 = 0x00;
    pub const MODULE_OK: u8 = 0x01;
    pub const CHEAT_CHECKS_RESULT: u8 = 0x02;
    pub const MEM_CHECKS_RESULT: u8 = 0x03;
    pub const HASH_RESULT: u8 = 0x04;
    pub const MODULE_FAILED: u8 = 0x05;
}

/// A decrypted server message, far enough parsed to say what it wants.
#[derive(Debug)]
pub enum ServerMessage {
    /// Load this module: 16-byte id, 16-byte key, and its compressed size.
    ModuleUse {
        id: [u8; 16],
        key: [u8; 16],
        size: u32,
    },
    /// One chunk of the module transfer.
    ModuleCache { chunk: Vec<u8> },
    /// The module is in place; the checks follow.
    ModuleInitialize,
    /// A scan request. The body is the module's own encoding, so it is carried raw until the
    /// module's check layout is implemented.
    CheatChecksRequest { body: Vec<u8> },
    /// Prove which module we hold.
    HashRequest { seed: Vec<u8> },
    /// An opcode this client does not model — carried whole so a caller can log it rather than
    /// guess. A value outside `server_op` here almost always means the keys are wrong, not that the
    /// server invented an opcode.
    Unknown { opcode: u8, body: Vec<u8> },
}

/// Parse one **already decrypted** `SMSG_WARDEN_DATA` body.
pub fn parse_server_message(body: &[u8]) -> Option<ServerMessage> {
    let (&opcode, rest) = body.split_first()?;
    Some(match opcode {
        server_op::MODULE_USE if rest.len() >= 36 => {
            let mut id = [0u8; 16];
            let mut key = [0u8; 16];
            id.copy_from_slice(&rest[..16]);
            key.copy_from_slice(&rest[16..32]);
            ServerMessage::ModuleUse {
                id,
                key,
                size: u32::from_le_bytes([rest[32], rest[33], rest[34], rest[35]]),
            }
        }
        server_op::MODULE_CACHE => ServerMessage::ModuleCache {
            chunk: rest.to_vec(),
        },
        server_op::MODULE_INITIALIZE => ServerMessage::ModuleInitialize,
        server_op::CHEAT_CHECKS_REQUEST => ServerMessage::CheatChecksRequest {
            body: rest.to_vec(),
        },
        server_op::HASH_REQUEST => ServerMessage::HashRequest {
            seed: rest.to_vec(),
        },
        other => ServerMessage::Unknown {
            opcode: other,
            body: rest.to_vec(),
        },
    })
}
