//! Warden anticheat — the client half of the `SMSG_WARDEN_DATA` / `CMSG_WARDEN_DATA` exchange.
//!
//! **Scope, stated up front because it bounds what this can ever do.** A Warden scan set is chosen
//! server-side per session and its checks are typed (`WardenScan.hpp`'s `WindowsScanType`). Of those
//! types, the ones this client can answer are the ones it can *witness about itself*:
//! `HASH_CLIENT_FILE` (it holds the real game files) and `GET_LUA_VARIABLE` (it holds a real Lua VM).
//! `READ_MEMORY`, `FIND_CODE_BY_HASH` and `FIND_MEM_IMAGE_CODE_BY_HASH` ask for bytes at addresses
//! inside `WoW.exe`; benilla is a from-scratch client and has no such image, so it cannot answer them
//! — and answering them from a copy of that binary would mean the check no longer says anything about
//! the client that is actually running. A server that wants to admit this client therefore needs a
//! scan profile made of the witnessable types; `WardenScanMgr::GetRandomScans` already selects by the
//! session's build flag, so that is a database question, not a protocol one.
//!
//! **The crypto is ported from the server it has to interoperate with**, not from memory:
//! `SHA1Randx` is a line-for-line port of tortoise-wow
//! `src/game/Anticheat/Warden/WardenKeyGeneration.h`, and the key direction is read off
//! `Warden.cpp`: the server inits `_inputCrypto` with the FIRST 16 generated bytes and decrypts
//! client→server traffic with it (`DecryptData`, `Warden.cpp:316-319`), and inits `_outputCrypto`
//! with the SECOND 16 for server→client (`EncryptData`, `:321-324`). Mirrored here, so this client
//! encrypts with key #1 and decrypts with key #2. Getting that pair backwards is the failure mode
//! this comment exists to prevent: it does not error, it just yields plausible-looking garbage.
//!
//! There is a second keying step: once a module is loaded the server re-inits both ciphers from the
//! module's own `clientKey`/`serverKey` (`Warden.cpp:141-142`). [`WardenCrypto::rekey`] is that step.

use sha1::{Digest, Sha1};

/// `SHA1Randx` — the server's key-stream generator over the session key
/// (`WardenKeyGeneration.h`). Hash the first half into `o1` and the second into `o2`, then emit
/// 20-byte blocks of `SHA1(o1 ‖ o0 ‖ o2)`, feeding each block back in as the next `o0`.
struct Sha1Randx {
    o0: [u8; 20],
    o1: [u8; 20],
    o2: [u8; 20],
    taken: usize,
}

impl Sha1Randx {
    fn new(seed: &[u8]) -> Self {
        let half = seed.len() / 2;
        let o1: [u8; 20] = Sha1::digest(&seed[..half]).into();
        let o2: [u8; 20] = Sha1::digest(&seed[half..]).into();
        let mut s = Sha1Randx {
            o0: [0u8; 20],
            o1,
            o2,
            taken: 0,
        };
        s.fill_up();
        s
    }

    fn fill_up(&mut self) {
        let mut sha = Sha1::new();
        sha.update(self.o1);
        sha.update(self.o0);
        sha.update(self.o2);
        self.o0 = sha.finalize().into();
        self.taken = 0;
    }

    /// The server's `Generate`: refill only when the current block is spent, then take one byte.
    fn generate(&mut self, out: &mut [u8]) {
        for byte in out.iter_mut() {
            if self.taken == 20 {
                self.fill_up();
            }
            *byte = self.o0[self.taken];
            self.taken += 1;
        }
    }
}

/// RC4/ARC4 — the stream cipher both Warden directions run on (`Auth/ARC4`). Stateful: each call
/// continues the keystream, so one instance belongs to exactly one direction of one session.
pub struct Rc4 {
    s: [u8; 256],
    i: u8,
    j: u8,
}

impl Rc4 {
    pub fn new(key: &[u8]) -> Self {
        let mut s = [0u8; 256];
        for (i, v) in s.iter_mut().enumerate() {
            *v = i as u8;
        }
        let mut j = 0u8;
        for i in 0..256 {
            j = j
                .wrapping_add(s[i])
                .wrapping_add(key[i % key.len()]);
            s.swap(i, j as usize);
        }
        Rc4 { s, i: 0, j: 0 }
    }

    /// XOR `buf` with the next keystream bytes, in place. RC4 is symmetric — the same call both
    /// encrypts and decrypts.
    pub fn apply(&mut self, buf: &mut [u8]) {
        for byte in buf.iter_mut() {
            self.i = self.i.wrapping_add(1);
            self.j = self.j.wrapping_add(self.s[self.i as usize]);
            self.s.swap(self.i as usize, self.j as usize);
            let k = self.s[self.i as usize].wrapping_add(self.s[self.j as usize]);
            *byte ^= self.s[k as usize];
        }
    }
}

/// The bytes generated per direction (`Warden::Warden`'s `KeyLength`).
const KEY_LENGTH: usize = 16;

/// Both directions of one Warden session.
pub struct WardenCrypto {
    /// Applied to what we SEND — the server decrypts it with its `_inputCrypto`.
    outgoing: Rc4,
    /// Applied to what we RECEIVE — the server encrypted it with its `_outputCrypto`.
    incoming: Rc4,
}

impl WardenCrypto {
    /// Derive both ciphers from the SRP6 session key, exactly as `Warden::Warden` does.
    pub fn from_session_key(session_key: &[u8]) -> Self {
        let mut rand = Sha1Randx::new(session_key);
        let mut first = [0u8; KEY_LENGTH];
        let mut second = [0u8; KEY_LENGTH];
        rand.generate(&mut first);
        rand.generate(&mut second);
        WardenCrypto {
            outgoing: Rc4::new(&first),
            incoming: Rc4::new(&second),
        }
    }

    /// Re-key from a loaded module's own pair (`Warden.cpp:141-142`). `client_key` is the one the
    /// server will decrypt our traffic with, so it is ours to encrypt with.
    pub fn rekey(&mut self, client_key: &[u8], server_key: &[u8]) {
        self.outgoing = Rc4::new(client_key);
        self.incoming = Rc4::new(server_key);
    }

    pub fn decrypt(&mut self, buf: &mut [u8]) {
        self.incoming.apply(buf);
    }

    pub fn encrypt(&mut self, buf: &mut [u8]) {
        self.outgoing.apply(buf);
    }
}

/// Server→client Warden opcodes — the first byte of a decrypted `SMSG_WARDEN_DATA` body.
///
/// Their numbering is the oracle for whether [`WardenCrypto`] is keyed correctly: a correct decrypt
/// puts a value in `0..=4` here, a swapped key pair puts noise. That is the check to run first
/// against a live server, since no fixture can stand in for the server's own keystream.
pub mod server_op {
    pub const MODULE_USE: u8 = 0x00;
    pub const MODULE_CACHE: u8 = 0x01;
    pub const CHEAT_CHECKS_REQUEST: u8 = 0x02;
    pub const MODULE_INITIALIZE: u8 = 0x03;
    pub const MEM_CHECKS_REQUEST: u8 = 0x04;
    pub const HASH_REQUEST: u8 = 0x05;
}

/// Client→server Warden opcodes — the first byte of a `CMSG_WARDEN_DATA` body we send.
pub mod client_op {
    pub const MODULE_MISSING: u8 = 0x00;
    pub const MODULE_OK: u8 = 0x01;
    pub const CHEAT_CHECKS_RESULT: u8 = 0x02;
    pub const MEM_CHECKS_RESULT: u8 = 0x03;
    pub const HASH_RESULT: u8 = 0x04;
    pub const MODULE_FAILED: u8 = 0x05;
}

/// A decrypted server message, far enough parsed to say what it wants.
#[derive(Debug)]
pub enum ServerMessage {
    /// Load this module: 16-byte id, 16-byte key, and its compressed size.
    ModuleUse {
        id: [u8; 16],
        key: [u8; 16],
        size: u32,
    },
    /// One chunk of the module transfer.
    ModuleCache { chunk: Vec<u8> },
    /// The module is in place; the checks follow.
    ModuleInitialize,
    /// A scan request. The body is the module's own encoding, so it is carried raw until the
    /// module's check layout is implemented.
    CheatChecksRequest { body: Vec<u8> },
    /// Prove which module we hold.
    HashRequest { seed: Vec<u8> },
    /// An opcode this client does not model — carried whole so a caller can log it rather than
    /// guess. A value outside `server_op` here almost always means the keys are wrong, not that the
    /// server invented an opcode.
    Unknown { opcode: u8, body: Vec<u8> },
}

/// Parse one **already decrypted** `SMSG_WARDEN_DATA` body.
pub fn parse_server_message(body: &[u8]) -> Option<ServerMessage> {
    let (&opcode, rest) = body.split_first()?;
    Some(match opcode {
        server_op::MODULE_USE if rest.len() >= 36 => {
            let mut id = [0u8; 16];
            let mut key = [0u8; 16];
            id.copy_from_slice(&rest[..16]);
            key.copy_from_slice(&rest[16..32]);
            ServerMessage::ModuleUse {
                id,
                key,
                size: u32::from_le_bytes([rest[32], rest[33], rest[34], rest[35]]),
            }
        }
        server_op::MODULE_CACHE => ServerMessage::ModuleCache {
            chunk: rest.to_vec(),
        },
        server_op::MODULE_INITIALIZE => ServerMessage::ModuleInitialize,
        server_op::CHEAT_CHECKS_REQUEST => ServerMessage::CheatChecksRequest {
            body: rest.to_vec(),
        },
        server_op::HASH_REQUEST => ServerMessage::HashRequest {
            seed: rest.to_vec(),
        },
        other => ServerMessage::Unknown {
            opcode: other,
            body: rest.to_vec(),
        },
    })
}

// --- the scan lane -------------------------------------------------------------------------------
//
// Everything above is the transport. What follows is what a scan request MEANS, and it is written
// against a contract this client cannot read off the wire on its own: the byte that names a check's
// type is `module->opcodes[type] ^ xor` (`WardenScan.cpp`'s builders), and that table lives inside
// the module. A client that does not execute the module therefore cannot dispatch a request built
// the stock way — so this lane is written for a server profile that fixes the encoding instead, and
// [`CheckType`] is the mapping it proposes.

/// The scan types, numbered as `WindowsScanType` numbers them (`WardenScan.hpp:42-53`). The wire
/// byte is NOT this value on a stock server — see the note above — but the enum is the server's, so
/// a fixed-encoding profile has an obvious mapping to adopt.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckType {
    ReadMemory = 0,
    FindModuleByName = 1,
    FindMemImageCodeByHash = 2,
    FindCodeByHash = 3,
    HashClientFile = 4,
    GetLuaVariable = 5,
    ApiCheck = 6,
    FindDriverByName = 7,
    CheckTimingValues = 8,
}

impl CheckType {
    pub fn from_u8(v: u8) -> Option<Self> {
        Some(match v {
            0 => CheckType::ReadMemory,
            1 => CheckType::FindModuleByName,
            2 => CheckType::FindMemImageCodeByHash,
            3 => CheckType::FindCodeByHash,
            4 => CheckType::HashClientFile,
            5 => CheckType::GetLuaVariable,
            6 => CheckType::ApiCheck,
            7 => CheckType::FindDriverByName,
            8 => CheckType::CheckTimingValues,
            _ => return None,
        })
    }

    /// Can this client witness the answer *about itself*?
    ///
    /// The three `false` rows are not unimplemented work — they are questions about the contents of
    /// a `WoW.exe` process image, asked of a client that is not one. There is no state in this
    /// program that constitutes an answer, so the only way to produce one is to copy it from
    /// somewhere else, and a copied answer says nothing about the client that sent it. They are
    /// therefore permanently [`ScanOutcome::Unanswerable`], and a profile that includes them is
    /// asking for an answer that could not mean anything.
    pub fn is_witnessable(self) -> bool {
        match self {
            // Reads of a PE image this client does not have.
            CheckType::ReadMemory | CheckType::FindMemImageCodeByHash | CheckType::FindCodeByHash => {
                false
            }
            // Real files we hold, and our own Lua VM: these say something about us.
            CheckType::HashClientFile | CheckType::GetLuaVariable => true,
            // Process/driver/API surfaces a browser sandbox does not have. Answerable truthfully —
            // the honest answer is always "absent" — but that makes them free to pass and therefore
            // worth nothing as checks. Reported so a profile author can see they are noise.
            CheckType::FindModuleByName | CheckType::FindDriverByName | CheckType::ApiCheck => true,
            CheckType::CheckTimingValues => true,
        }
    }
}

/// What answering one check produced.
#[derive(Debug, PartialEq, Eq)]
pub enum ScanOutcome {
    /// The bytes to put in `CHEAT_CHECKS_RESULT` for this check, in request order.
    Answered(Vec<u8>),
    /// No answer exists for this client. Carries the reason so it reaches a log rather than
    /// becoming a silent zero — a silent wrong answer is indistinguishable from a cheat.
    Unanswerable(&'static str),
}

/// What one check asked for, with the fields ITS layout carries.
///
/// Not a single string: each scan has its own request shape (`WardenScan.cpp`'s builders), and
/// flattening them would throw away the fields an answer has to be computed from — the HMAC seed a
/// module lookup is keyed by, the offset and width a memory read wants, the two string indices an
/// API check uses.
#[derive(Debug, PartialEq, Eq)]
pub enum ScanParams {
    /// `READ_MEMORY`, `FIND_CODE_BY_HASH`, `FIND_MEM_IMAGE_CODE_BY_HASH` — everything that reads a
    /// `WoW.exe` process image. The fields are carried for logging only; there is no answer.
    Image,
    /// `HASH_CLIENT_FILE`: `u8 string_index`.
    FileHash { path: String },
    /// `GET_LUA_VARIABLE`: `u8 string_index`.
    LuaVariable { name: String },
    /// `FIND_MODULE_BY_NAME`: `u32 seed`, then `HMAC-SHA1(seed, UPPERCASE NAME)[20]`. The name
    /// itself never crosses the wire.
    ModulePresence { seed: u32, name_digest: [u8; 20] },
    /// `FIND_DRIVER_BY_NAME`: `u32 seed`, `HMAC-SHA1(seed, target path)[20]`, `u8 string_index`
    /// naming the device.
    DriverPresence {
        seed: u32,
        path_digest: [u8; 20],
        name: String,
    },
    /// `API_CHECK`: `u32 seed`, `hash[20]`, `u8 module_index`, `u8 proc_index`, `u32 offset`,
    /// `u8 length` — both indices 1-based, and the module's is `strings.size() - 1` because the
    /// builder pushes the module then the proc.
    ApiCheck {
        module: String,
        proc: String,
        hash: [u8; 20],
        offset: u32,
        length: u8,
    },
    /// `CHECK_TIMING_VALUES`: no payload.
    Timing,
}

/// A decoded check: its type, and the fields its own layout carries.
#[derive(Debug, PartialEq, Eq)]
pub struct ScanRequest {
    pub check: CheckType,
    pub params: ScanParams,
}

/// What one attestation produced.
///
/// `NotImplemented` is kept as its own state on purpose: "there is no such file" is an ANSWER the
/// client witnessed, while "we never wrote the file-hashing path" is a GAP. Collapsing them would
/// make every unimplemented check report a clean result — a silent no-op that reads as a pass,
/// which is the one failure mode this lane must not have.
///
/// There is deliberately no `Absent` variant. A witness that looked and found nothing still returns
/// `Present`, with the "not found" state expressed INSIDE the scan's own reply structure, because
/// the server reads a fixed number of bytes per scan and matches them positionally. A shorter reply
/// does not read as "nothing found" — it desynchronises every scan after it in the same packet.
#[derive(Debug, PartialEq, Eq)]
pub enum Attestation<T> {
    /// The client looked, and this is what it saw — including "not there", expressed inside `T`.
    Present(T),
    /// The client cannot say. Never becomes an answer; it becomes an
    /// [`ScanOutcome::Unanswerable`] that names itself.
    NotImplemented,
}

/// The marker three scans use for "found", and it is NOT 1: `WindowsModuleScan::ModuleFound`,
/// `WindowsDriverScan::Found` and `WindowsHookScan::Detoured` are all `0x4A` (`WardenScan.hpp:112`,
/// `:201`, `:183`), and their checkers test equality against it. Anything else means not found.
pub const FOUND_0X4A: u8 = 0x4A;
const NOT_0X4A: u8 = 0x00;

/// The two string-shaped scans invert that: their checkers read `found = !buff.read<uint8>()`
/// (`WardenScan.cpp:224`, `:264`), so ZERO means found.
const ZERO_MEANS_FOUND: u8 = 0x00;
const NONZERO_MEANS_ABSENT: u8 = 0x01;

/// `HASH_CLIENT_FILE`'s reply: a found byte then the digest.
///
/// The digest is sent even when `found` is false, because the server sizes this reply as
/// `sizeof(uint8) + SHA_DIGEST_LENGTH` — a fixed 21 bytes — and results are positional. Zeroes are
/// the honest filler there: not an answer to anything, just the unread remainder of a reply whose
/// width the server already decided.
#[derive(Debug, PartialEq, Eq)]
pub struct FileHash {
    pub found: bool,
    pub sha1: [u8; 20],
}

/// `GET_LUA_VARIABLE`'s reply: a found byte, then a length-prefixed value when found.
#[derive(Debug, PartialEq, Eq)]
pub struct LuaValue {
    pub found: bool,
    pub value: String,
}

/// `FIND_MODULE_BY_NAME`'s reply — one byte, compared against `0x4A`.
///
/// Note what the request does NOT carry: the module's name never goes over the wire. The server
/// sends a `u32` seed and `HMAC-SHA1(seed, NAME)` (`WardenScan.cpp:30-36`), so a client answers by
/// running that HMAC over the names it knows and looking for the digest. A witness that cannot
/// enumerate its own modules can therefore only ever say "not found", which is exactly why this
/// scan is free to pass in a browser and worth nothing there as a check.
#[derive(Debug, PartialEq, Eq)]
pub struct ModulePresence {
    pub found: bool,
}

/// `FIND_DRIVER_BY_NAME`'s reply — one byte against `0x4A`. Same HMAC'd-name shape as
/// [`ModulePresence`], plus a string index carrying the device name.
#[derive(Debug, PartialEq, Eq)]
pub struct DriverPresence {
    pub found: bool,
}

/// `API_CHECK`'s reply — one byte against `0x4A`, true when the examined export is detoured.
#[derive(Debug, PartialEq, Eq)]
pub struct ApiIntegrity {
    pub detoured: bool,
}

/// `CHECK_TIMING_VALUES`' reply — `u8 + u32`, five bytes, per the scan's declared reply size. The
/// scan calls the game's own clock and `GetTickCount`; `WindowsTimeScan`'s own comment notes that a
/// mismatch is NOT by itself grounds to call it a hack.
#[derive(Debug, PartialEq, Eq)]
pub struct TimingValues {
    pub mismatch: bool,
    pub ticks: u32,
}

/// What the client can consult to answer a check about itself.
///
/// One method per witnessable scan type, every one defaulting to [`Attestation::NotImplemented`] so
/// an implementor adds them at their own pace and an unwritten one is NAMED rather than silently
/// passing. Each returns the scan's own reply STRUCTURE rather than a boolean, so every field the
/// server reads has to be produced deliberately: the widths are fixed and the results positional,
/// so a missing field is not a blank, it is a shifted packet.
///
/// There is deliberately no method for `READ_MEMORY`, `FIND_CODE_BY_HASH` or
/// `FIND_MEM_IMAGE_CODE_BY_HASH`: those ask for the contents of a `WoW.exe` process image, and no
/// implementation of this trait can witness one, so a stub for them would be a slot for a value
/// copied from elsewhere rather than a gap waiting to be filled.
pub trait ScanWitness {
    /// SHA-1 of the named client file as this client actually holds it. Hash what was DOWNLOADED,
    /// not what a host says it served — the answer has to be a fact about this client.
    fn hash_client_file(&self, _path: &str) -> Attestation<FileHash> {
        Attestation::NotImplemented
    }

    /// The value of a Lua global in this client's own VM.
    fn lua_variable(&self, _name: &str) -> Attestation<LuaValue> {
        Attestation::NotImplemented
    }

    /// Is a module whose name HMACs to `name_digest` under `seed` loaded in this client? See
    /// [`ModulePresence`] for why the name itself is not available.
    fn module_loaded(&self, _seed: u32, _name_digest: &[u8; 20]) -> Attestation<ModulePresence> {
        Attestation::NotImplemented
    }

    /// The driver form of [`Self::module_loaded`]. `name` is the device name the request carried in
    /// its string table; the target path is the HMAC'd part.
    fn driver_loaded(
        &self,
        _seed: u32,
        _path_digest: &[u8; 20],
        _name: &str,
    ) -> Attestation<DriverPresence> {
        Attestation::NotImplemented
    }

    /// Has `proc` in `module` been detoured? `hash` is the digest the server expects over `length`
    /// bytes at `offset` past the jump target.
    fn api_detoured(
        &self,
        _module: &str,
        _proc: &str,
        _hash: &[u8; 20],
        _offset: u32,
        _length: u8,
    ) -> Attestation<ApiIntegrity> {
        Attestation::NotImplemented
    }

    /// The client's clock comparison.
    fn timing_values(&self) -> Attestation<TimingValues> {
        Attestation::NotImplemented
    }
}

/// Answer one check. Gaps and structural impossibilities are both named, never faked.
pub fn answer(request: &ScanRequest, witness: &dyn ScanWitness) -> ScanOutcome {
    match &request.params {
        ScanParams::Image => ScanOutcome::Unanswerable(
            "this scan reads a WoW.exe process image; this client has none",
        ),
        ScanParams::FileHash { path } => match witness.hash_client_file(path) {
            Attestation::Present(r) => {
                let mut out = Vec::with_capacity(1 + r.sha1.len());
                out.push(if r.found {
                    ZERO_MEANS_FOUND
                } else {
                    NONZERO_MEANS_ABSENT
                });
                out.extend_from_slice(&r.sha1);
                ScanOutcome::Answered(out)
            }
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::hash_client_file is not implemented")
            }
        },
        ScanParams::LuaVariable { name } => match witness.lua_variable(name) {
            Attestation::Present(r) if !r.found => {
                ScanOutcome::Answered(vec![NONZERO_MEANS_ABSENT])
            }
            Attestation::Present(r) => {
                let len = r.value.len().min(u8::MAX as usize);
                let mut out = Vec::with_capacity(2 + len);
                out.push(ZERO_MEANS_FOUND);
                out.push(len as u8);
                out.extend_from_slice(&r.value.as_bytes()[..len]);
                ScanOutcome::Answered(out)
            }
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::lua_variable is not implemented")
            }
        },
        ScanParams::ModulePresence { seed, name_digest } => {
            match witness.module_loaded(*seed, name_digest) {
                Attestation::Present(r) => ScanOutcome::Answered(vec![marker(r.found)]),
                Attestation::NotImplemented => {
                    ScanOutcome::Unanswerable("ScanWitness::module_loaded is not implemented")
                }
            }
        }
        ScanParams::DriverPresence {
            seed,
            path_digest,
            name,
        } => match witness.driver_loaded(*seed, path_digest, name) {
            Attestation::Present(r) => ScanOutcome::Answered(vec![marker(r.found)]),
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::driver_loaded is not implemented")
            }
        },
        ScanParams::ApiCheck {
            module,
            proc,
            hash,
            offset,
            length,
        } => match witness.api_detoured(module, proc, hash, *offset, *length) {
            Attestation::Present(r) => ScanOutcome::Answered(vec![marker(r.detoured)]),
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::api_detoured is not implemented")
            }
        },
        ScanParams::Timing => match witness.timing_values() {
            Attestation::Present(r) => {
                let mut out = Vec::with_capacity(5);
                out.push(u8::from(r.mismatch));
                out.extend_from_slice(&r.ticks.to_le_bytes());
                ScanOutcome::Answered(out)
            }
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::timing_values is not implemented")
            }
        },
    }
}

/// The one-byte reply the `0x4A` scans use.
fn marker(found: bool) -> u8 {
    if found {
        FOUND_0X4A
    } else {
        NOT_0X4A
    }
}

// --- request framing -----------------------------------------------------------------------------
//
// `Warden::RequestScans` (`Warden.cpp:246-274`) assembles a Windows request as:
//
//     u8  CHEAT_CHECKS_REQUEST
//     string table: repeated { u8 len, bytes[len] }, terminated by a single u8 0
//     the scan block: each scan's own bytes, back to back
//     u8  module->scanTerminator ^ xor
//
// and each scan begins with `module->opcodes[type] ^ xor`. Both bytes come from the module, which is
// why `decode_type` and `terminator` are parameters here rather than constants: a profile that fixes
// the encoding supplies them, and nothing in this file has to guess.
//
// The two witnessable scans share one payload: `u8 string_index`, 1-based because the server takes
// `strings.size()` AFTER pushing (`WardenScan.cpp:214-219` and `:254-259`). Layouts for the other
// types are deliberately not modelled — we have not read them, and inventing one would desync the
// walk rather than fail it.

/// Why a request could not be read. A parse that stops is worth more than one that guesses: the
/// scan block has no per-scan length, so a wrong payload width silently turns the rest of the
/// packet into nonsense.
#[derive(Debug, PartialEq, Eq)]
pub enum RequestError {
    Truncated(&'static str),
    /// A type byte `decode_type` did not recognise.
    UnknownType(u8),
    /// A type we can recognise but whose payload layout this client has not modelled, so the walk
    /// cannot continue past it.
    UnmodelledPayload(CheckType),
    /// A scan referenced a string index the table does not have.
    BadStringIndex(u8),
}

/// Parse a decrypted `CHEAT_CHECKS_REQUEST` body (opcode byte already stripped).
///
/// Every layout below is read off the matching builder in `WardenScan.cpp`, because the scan block
/// carries NO per-scan length: the walk advances by exactly what each type's fields occupy, so a
/// width taken on trust does not fail here — it turns every later scan in the packet into
/// plausible nonsense. The two code-by-hash scans are the one gap, and they stop the walk.
pub fn parse_checks_request(
    body: &[u8],
    decode_type: &dyn Fn(u8) -> Option<CheckType>,
    terminator: u8,
) -> Result<Vec<ScanRequest>, RequestError> {
    let mut at = 0usize;
    let mut strings: Vec<String> = Vec::new();
    loop {
        let len = *body.get(at).ok_or(RequestError::Truncated("string table"))? as usize;
        at += 1;
        if len == 0 {
            break;
        }
        let end = at + len;
        let raw = body.get(at..end).ok_or(RequestError::Truncated("string"))?;
        strings.push(String::from_utf8_lossy(raw).into_owned());
        at = end;
    }

    // 1-based, because every builder takes `strings.size()` AFTER pushing its own.
    let pick = |index: u8, strings: &Vec<String>| -> Result<String, RequestError> {
        strings
            .get((index as usize).wrapping_sub(1))
            .cloned()
            .ok_or(RequestError::BadStringIndex(index))
    };
    let take = |at: &mut usize, n: usize| -> Result<Vec<u8>, RequestError> {
        let out = body
            .get(*at..*at + n)
            .ok_or(RequestError::Truncated("scan field"))?
            .to_vec();
        *at += n;
        Ok(out)
    };
    let u8_at = |at: &mut usize| -> Result<u8, RequestError> {
        let v = *body.get(*at).ok_or(RequestError::Truncated("scan field"))?;
        *at += 1;
        Ok(v)
    };
    let u32_at = |at: &mut usize| -> Result<u32, RequestError> {
        let b = take(at, 4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    };
    let digest_at = |at: &mut usize| -> Result<[u8; 20], RequestError> {
        let b = take(at, 20)?;
        let mut d = [0u8; 20];
        d.copy_from_slice(&b);
        Ok(d)
    };

    let mut out = Vec::new();
    loop {
        let byte = *body.get(at).ok_or(RequestError::Truncated("scan block"))?;
        at += 1;
        if byte == terminator {
            return Ok(out);
        }
        let check = decode_type(byte).ok_or(RequestError::UnknownType(byte))?;
        let params = match check {
            CheckType::HashClientFile => ScanParams::FileHash {
                path: pick(u8_at(&mut at)?, &strings)?,
            },
            CheckType::GetLuaVariable => ScanParams::LuaVariable {
                name: pick(u8_at(&mut at)?, &strings)?,
            },
            CheckType::FindModuleByName => ScanParams::ModulePresence {
                seed: u32_at(&mut at)?,
                name_digest: digest_at(&mut at)?,
            },
            CheckType::FindDriverByName => {
                let seed = u32_at(&mut at)?;
                let path_digest = digest_at(&mut at)?;
                ScanParams::DriverPresence {
                    seed,
                    path_digest,
                    name: pick(u8_at(&mut at)?, &strings)?,
                }
            }
            CheckType::ApiCheck => {
                let _seed = u32_at(&mut at)?;
                let hash = digest_at(&mut at)?;
                let module = pick(u8_at(&mut at)?, &strings)?;
                let proc = pick(u8_at(&mut at)?, &strings)?;
                ScanParams::ApiCheck {
                    module,
                    proc,
                    hash,
                    offset: u32_at(&mut at)?,
                    length: u8_at(&mut at)?,
                }
            }
            CheckType::CheckTimingValues => ScanParams::Timing,
            // `u8 string_index` (0 when the form carries no module), `u32 offset`, `u8 length`. The
            // fields are consumed so the walk stays aligned even though the scan is unanswerable.
            CheckType::ReadMemory => {
                let _module_index = u8_at(&mut at)?;
                let _offset = u32_at(&mut at)?;
                let _length = u8_at(&mut at)?;
                ScanParams::Image
            }
            // The code scans' builder is the one we have not read; guessing its width would
            // silently corrupt the rest of the block, so the walk stops instead.
            other @ (CheckType::FindCodeByHash | CheckType::FindMemImageCodeByHash) => {
                return Err(RequestError::UnmodelledPayload(other))
            }
        };
        out.push(ScanRequest { check, params });
    }
}

/// The server's `BuildChecksum` (`Warden.cpp:351-362`): SHA-1 over the result payload, then the five
/// 32-bit words of the digest XORed together, little-endian.
pub fn checks_result_checksum(payload: &[u8]) -> u32 {
    let hash: [u8; 20] = Sha1::digest(payload).into();
    let mut sum = 0u32;
    for word in hash.chunks_exact(4) {
        sum ^= u32::from_le_bytes([word[0], word[1], word[2], word[3]]);
    }
    sum
}

/// Assemble `CHEAT_CHECKS_RESULT`: `u8 opcode, u16 length, u32 checksum, payload`, the order the
/// server reads it in (`Warden.cpp:425-429`).
///
/// Refuses to build when any outcome is [`ScanOutcome::Unanswerable`], carrying that reason out.
/// There is no filler byte that would be honest here — the server matches results to the scans it
/// sent, positionally, so a placeholder is not a gap in the reply, it is a false answer to a
/// specific question.
pub fn build_checks_result(outcomes: &[ScanOutcome]) -> Result<Vec<u8>, &'static str> {
    let mut payload = Vec::new();
    for outcome in outcomes {
        match outcome {
            ScanOutcome::Answered(bytes) => payload.extend_from_slice(bytes),
            ScanOutcome::Unanswerable(reason) => return Err(reason),
        }
    }
    let mut packet = Vec::with_capacity(1 + 2 + 4 + payload.len());
    packet.push(client_op::CHEAT_CHECKS_RESULT);
    packet.extend_from_slice(&(payload.len() as u16).to_le_bytes());
    packet.extend_from_slice(&checks_result_checksum(&payload).to_le_bytes());
    packet.extend_from_slice(&payload);
    Ok(packet)
}

/// A complete [`ScanWitness`] for this client, built from the three things only the client can
/// supply. Everything else — hashing, the reply shapes, what is truthfully absent — is decided here
/// so no caller has to get it right twice.
///
/// The seam is closures rather than concrete types because `benilla-protocol` has no business
/// depending on the MPQ chain or the Lua VM; the app hands in `Chain::read` and a globals lookup.
pub struct ClientWitness {
    read_file: Box<dyn Fn(&str) -> Option<Vec<u8>> + Send>,
    lua_global: Box<dyn Fn(&str) -> Option<String> + Send>,
    clocks: Box<dyn Fn() -> (u32, u32) + Send>,
}

impl ClientWitness {
    /// `read_file` reads a client file as this client holds it; `lua_global` reads a global from its
    /// own Lua state; `clocks` returns the game's own millisecond clock and an independent one.
    pub fn new(
        read_file: Box<dyn Fn(&str) -> Option<Vec<u8>> + Send>,
        lua_global: Box<dyn Fn(&str) -> Option<String> + Send>,
        clocks: Box<dyn Fn() -> (u32, u32) + Send>,
    ) -> Self {
        ClientWitness {
            read_file,
            lua_global,
            clocks,
        }
    }
}

impl ScanWitness for ClientWitness {
    /// Hash what the client HOLDS. The bytes come from the same reader the client renders from, so
    /// the digest describes the client that is running rather than what a host meant to serve it —
    /// which is the only reading under which this check means anything.
    fn hash_client_file(&self, path: &str) -> Attestation<FileHash> {
        Attestation::Present(match (self.read_file)(path) {
            Some(bytes) => FileHash {
                found: true,
                sha1: Sha1::digest(&bytes).into(),
            },
            None => FileHash {
                found: false,
                sha1: [0u8; 20],
            },
        })
    }

    fn lua_variable(&self, name: &str) -> Attestation<LuaValue> {
        Attestation::Present(match (self.lua_global)(name) {
            Some(value) => LuaValue { found: true, value },
            None => LuaValue {
                found: false,
                value: String::new(),
            },
        })
    }

    /// Always absent, and that is the TRUE answer rather than a convenient one: this client is not a
    /// Windows process with a module list — in a browser there is no such list at all, and natively
    /// it is a Rust binary whose modules have nothing to do with the ones these scans hunt for.
    ///
    /// Worth stating plainly for whoever builds a scan profile: a check whose answer is fixed
    /// regardless of the client's state detects nothing. Including it costs a round trip and buys
    /// no assurance. The same goes for [`Self::driver_loaded`] and [`Self::api_detoured`].
    fn module_loaded(&self, _seed: u32, _name_digest: &[u8; 20]) -> Attestation<ModulePresence> {
        Attestation::Present(ModulePresence { found: false })
    }

    /// Always absent — see [`Self::module_loaded`]. The scan asks `QueryDosDevice` about a driver;
    /// there is no such call to make here.
    fn driver_loaded(
        &self,
        _seed: u32,
        _path_digest: &[u8; 20],
        _name: &str,
    ) -> Attestation<DriverPresence> {
        Attestation::Present(DriverPresence { found: false })
    }

    /// Never detoured — see [`Self::module_loaded`]. The scan walks a Windows export looking for a
    /// `JMP` patched over its prologue; this client has no such export to walk.
    fn api_detoured(
        &self,
        _module: &str,
        _proc: &str,
        _hash: &[u8; 20],
        _offset: u32,
        _length: u8,
    ) -> Attestation<ApiIntegrity> {
        Attestation::Present(ApiIntegrity { detoured: false })
    }

    /// The one browser-shaped scan that says something real. The scan exists because the reference
    /// client's own clock and `GetTickCount` should agree, and a hooked timer makes them diverge; two
    /// independent clocks here carry the same meaning. `WindowsTimeScan`'s own comment warns that a
    /// mismatch is NOT by itself grounds to call it a hack, so this reports the disagreement and
    /// leaves the judgement to the server.
    fn timing_values(&self) -> Attestation<TimingValues> {
        let (game, independent) = (self.clocks)();
        Attestation::Present(TimingValues {
            mismatch: game != independent,
            ticks: game,
        })
    }
}

/// A server profile's fixed check encoding, plus the client's witness — everything
/// [`crate::WorldSession`] needs to take part in a scan round.
///
/// This exists because the stock encoding is unavailable to us: the byte naming a check's type is
/// `module->opcodes[type] ^ xor`, and that table lives inside the Warden module, which a
/// from-scratch client cannot load. A server willing to admit such a client fixes the encoding
/// instead, and states it here. `opcodes` is indexed by [`CheckType`], exactly mirroring the
/// module's own table so a profile author has an obvious thing to copy.
///
/// A session without a profile refuses Warden outright — which is the right default, because
/// guessing an encoding does not fail, it silently misreads every request.
pub struct WardenProfile {
    /// Wire byte for each [`CheckType`], indexed by its discriminant.
    pub opcodes: [u8; 9],
    /// The byte that ends the scan block (`module->scanTerminator ^ xor` on a stock server).
    pub terminator: u8,
    /// What the client can say about itself.
    pub witness: Box<dyn ScanWitness + Send>,
}

impl WardenProfile {
    /// Wire byte -> check type. `None` for a byte the profile does not define, which stops the walk
    /// rather than letting a misread request be answered.
    pub fn decode(&self, byte: u8) -> Option<CheckType> {
        self.opcodes
            .iter()
            .position(|&b| b == byte)
            .and_then(|i| CheckType::from_u8(i as u8))
    }
}

impl std::fmt::Debug for WardenProfile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WardenProfile")
            .field("opcodes", &self.opcodes)
            .field("terminator", &self.terminator)
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A profile's fixed encoding, standing in for the module's `opcodes[]` table. Deliberately not
    /// the identity map, so a mapping or index bug cannot hide behind a coincidence.
    const XOR: u8 = 0x5a;
    const TERMINATOR: u8 = 0xff ^ XOR;

    fn decode(byte: u8) -> Option<CheckType> {
        CheckType::from_u8(byte ^ XOR)
    }

    const TOC: &str = r"Interface\FrameXML\FrameXML.toc";

    /// One entry of [`TestWitness::detoured_apis`]: a detour is only reported when EVERY field of
    /// the request matches, so a test that changes one field proves that field reached the witness.
    struct DetouredApi {
        module: String,
        proc: String,
        hash: [u8; 20],
        offset: u32,
        length: u8,
    }

    /// A fully implemented witness, configured per test rather than hard-wired: it holds one file
    /// and one Lua global, and its module/driver/API/clock answers come from these fields. The
    /// default is the state a browser client would honestly report — nothing loaded, nothing
    /// detoured, a clock that agrees with itself.
    struct TestWitness {
        /// Digests of the module names this client would own, matched against the request's
        /// `name_digest` — the name itself never crosses the wire.
        loaded_modules: Vec<[u8; 20]>,
        /// The driver equivalent, matched against the request's `path_digest`.
        loaded_drivers: Vec<[u8; 20]>,
        detoured_apis: Vec<DetouredApi>,
        timing_mismatch: bool,
        timing_ticks: u32,
    }

    impl Default for TestWitness {
        fn default() -> Self {
            TestWitness {
                loaded_modules: Vec::new(),
                loaded_drivers: Vec::new(),
                detoured_apis: Vec::new(),
                timing_mismatch: false,
                timing_ticks: 0x0123_4567,
            }
        }
    }

    impl ScanWitness for TestWitness {
        fn hash_client_file(&self, path: &str) -> Attestation<FileHash> {
            Attestation::Present(if path == TOC {
                FileHash {
                    found: true,
                    sha1: Sha1::digest(b"toc").into(),
                }
            } else {
                FileHash {
                    found: false,
                    sha1: [0u8; 20],
                }
            })
        }

        fn lua_variable(&self, name: &str) -> Attestation<LuaValue> {
            Attestation::Present(if name == "UIParent" {
                LuaValue {
                    found: true,
                    value: "table".into(),
                }
            } else {
                LuaValue {
                    found: false,
                    value: String::new(),
                }
            })
        }

        fn module_loaded(
            &self,
            _seed: u32,
            name_digest: &[u8; 20],
        ) -> Attestation<ModulePresence> {
            Attestation::Present(ModulePresence {
                found: self.loaded_modules
                    .iter()
                    .any(|digest| digest == name_digest),
            })
        }

        fn driver_loaded(
            &self,
            _seed: u32,
            path_digest: &[u8; 20],
            _name: &str,
        ) -> Attestation<DriverPresence> {
            Attestation::Present(DriverPresence {
                found: self.loaded_drivers
                    .iter()
                    .any(|digest| digest == path_digest),
            })
        }

        fn api_detoured(
            &self,
            module: &str,
            proc: &str,
            hash: &[u8; 20],
            offset: u32,
            length: u8,
        ) -> Attestation<ApiIntegrity> {
            let detoured = self.detoured_apis.iter().any(|api| {
                api.module == module
                    && api.proc == proc
                    && api.hash == *hash
                    && api.offset == offset
                    && api.length == length
            });

            Attestation::Present(ApiIntegrity { detoured })
        }

        fn timing_values(&self) -> Attestation<TimingValues> {
            Attestation::Present(TimingValues {
                mismatch: self.timing_mismatch,
                ticks: self.timing_ticks,
            })
        }
    }


    /// The default trait bodies: a client that has implemented nothing must produce NAMED gaps, not
    /// clean passes. A silent `Answered` here would mean every unimplemented check reports "nothing
    /// wrong", which is the worst possible failure for an anticheat lane.
    struct EmptyWitness;
    impl ScanWitness for EmptyWitness {}

    fn ask(params: ScanParams, check: CheckType, witness: &dyn ScanWitness) -> ScanOutcome {
        answer(&ScanRequest { check, params }, witness)
    }

    #[test]
    fn an_unimplemented_witness_names_its_gaps_instead_of_passing() {
        let cases = [
            (CheckType::HashClientFile, ScanParams::FileHash { path: TOC.into() }),
            (
                CheckType::GetLuaVariable,
                ScanParams::LuaVariable { name: "UIParent".into() },
            ),
            (
                CheckType::FindModuleByName,
                ScanParams::ModulePresence { seed: 1, name_digest: [0; 20] },
            ),
            (
                CheckType::FindDriverByName,
                ScanParams::DriverPresence {
                    seed: 1,
                    path_digest: [0; 20],
                    name: "npf".into(),
                },
            ),
            (
                CheckType::ApiCheck,
                ScanParams::ApiCheck {
                    module: "Kernel32.dll".into(),
                    proc: "GetTickCount".into(),
                    hash: [0; 20],
                    offset: 0,
                    length: 8,
                },
            ),
            (CheckType::CheckTimingValues, ScanParams::Timing),
        ];
        for (check, params) in cases {
            match ask(params, check, &EmptyWitness) {
                ScanOutcome::Unanswerable(reason) => assert!(
                    reason.contains("not implemented"),
                    "{check:?} gap must name itself: {reason}"
                ),
                ScanOutcome::Answered(bytes) => {
                    panic!("{check:?} answered {bytes:?} with nothing implemented")
                }
            }
        }
    }

    /// Every field of every reply structure, against the server's own constants. The presence
    /// scans are the ones this pins hardest: their "found" marker is `0x4A`, NOT 1, and a reply of
    /// 1 would read to the server as "not found" — plausible, wrong, and invisible.
    #[test]
    fn each_reply_structure_serialises_field_by_field() {
        // HASH_CLIENT_FILE: found byte 0, then the digest. Fixed 21 bytes either way.
        let hit = ask(
            ScanParams::FileHash { path: TOC.into() },
            CheckType::HashClientFile,
            &TestWitness::default(),
        );
        let expected: [u8; 20] = Sha1::digest(b"toc").into();
        let ScanOutcome::Answered(bytes) = hit else {
            panic!("file hash must answer")
        };
        assert_eq!(bytes.len(), 21, "the server sizes this reply at 1 + 20");
        assert_eq!(bytes[0], ZERO_MEANS_FOUND, "zero means found for this scan");
        assert_eq!(&bytes[1..], &expected, "the digest must be the real one");

        let miss = ask(
            ScanParams::FileHash { path: "nope".into() },
            CheckType::HashClientFile,
            &TestWitness::default(),
        );
        let ScanOutcome::Answered(bytes) = miss else {
            panic!("a missing file is still an answer")
        };
        assert_eq!(bytes.len(), 21, "width is fixed even when not found");
        assert_eq!(bytes[0], NONZERO_MEANS_ABSENT);
        assert_eq!(&bytes[1..], &[0u8; 20], "no digest to report");

        // GET_LUA_VARIABLE: found byte, length, value.
        let lua = ask(
            ScanParams::LuaVariable { name: "UIParent".into() },
            CheckType::GetLuaVariable,
            &TestWitness::default(),
        );
        assert_eq!(
            lua,
            ScanOutcome::Answered(vec![
                ZERO_MEANS_FOUND,
                5,
                b't', b'a', b'b', b'l', b'e'
            ])
        );

        // The three 0x4A scans: one byte, and it must be 0x4A only when found.
        for (check, params) in [
            (
                CheckType::FindModuleByName,
                ScanParams::ModulePresence { seed: 7, name_digest: [1; 20] },
            ),
            (
                CheckType::FindDriverByName,
                ScanParams::DriverPresence {
                    seed: 7,
                    path_digest: [1; 20],
                    name: "npf".into(),
                },
            ),
            (
                CheckType::ApiCheck,
                ScanParams::ApiCheck {
                    module: "Kernel32.dll".into(),
                    proc: "GetTickCount".into(),
                    hash: [1; 20],
                    offset: 4,
                    length: 8,
                },
            ),
        ] {
            let out = ask(params, check, &TestWitness::default());
            let ScanOutcome::Answered(bytes) = out else {
                panic!("{check:?} must answer")
            };
            assert_eq!(bytes.len(), 1, "{check:?} replies with exactly one byte");
            assert_ne!(
                bytes[0], FOUND_0X4A,
                "{check:?} witness reported absent, so the byte must not be the found marker"
            );
        }
        assert_eq!(marker(true), 0x4A, "found is 0x4A, not 1");
        assert_ne!(marker(false), 0x4A);

        // CHECK_TIMING_VALUES: u8 + u32 little-endian, five bytes.
        let timing = ask(ScanParams::Timing, CheckType::CheckTimingValues, &TestWitness::default());
        let ScanOutcome::Answered(bytes) = timing else {
            panic!("timing must answer")
        };
        assert_eq!(bytes.len(), 5, "the server sizes this reply at 1 + 4");
        assert_eq!(bytes[0], 0, "no mismatch reported");
        assert_eq!(
            u32::from_le_bytes([bytes[1], bytes[2], bytes[3], bytes[4]]),
            0x0123_4567
        );
    }

    /// The POSITIVE side of the presence scans, which the default witness never reaches: a client
    /// that really does hold the module, the driver and a detoured export must answer `0x4A` for
    /// each. Without this the matching logic is never executed and only the "absent" byte is ever
    /// checked — a witness that always answered "not found" would pass every other test in here.
    #[test]
    fn a_witness_that_found_something_answers_with_the_0x4a_marker() {
        let witness = TestWitness {
            loaded_modules: vec![[0xAB; 20]],
            loaded_drivers: vec![[0xCD; 20]],
            detoured_apis: vec![DetouredApi {
                module: "Kernel32.dll".into(),
                proc: "GetTickCount".into(),
                hash: [0xEF; 20],
                offset: 16,
                length: 8,
            }],
            timing_mismatch: true,
            timing_ticks: 99,
        };

        let module = ask(
            ScanParams::ModulePresence {
                seed: 1,
                name_digest: [0xAB; 20],
            },
            CheckType::FindModuleByName,
            &witness,
        );
        assert_eq!(module, ScanOutcome::Answered(vec![FOUND_0X4A]));

        let driver = ask(
            ScanParams::DriverPresence {
                seed: 1,
                path_digest: [0xCD; 20],
                name: "npf.sys".into(),
            },
            CheckType::FindDriverByName,
            &witness,
        );
        assert_eq!(driver, ScanOutcome::Answered(vec![FOUND_0X4A]));

        let api = ScanParams::ApiCheck {
            module: "Kernel32.dll".into(),
            proc: "GetTickCount".into(),
            hash: [0xEF; 20],
            offset: 16,
            length: 8,
        };
        assert_eq!(
            ask(api, CheckType::ApiCheck, &witness),
            ScanOutcome::Answered(vec![FOUND_0X4A])
        );

        // One field off is a different question, and must answer "not detoured" — this is what
        // proves every field actually reached the witness rather than being ignored.
        let wrong_offset = ScanParams::ApiCheck {
            module: "Kernel32.dll".into(),
            proc: "GetTickCount".into(),
            hash: [0xEF; 20],
            offset: 17,
            length: 8,
        };
        let ScanOutcome::Answered(bytes) = ask(wrong_offset, CheckType::ApiCheck, &witness) else {
            panic!("must answer")
        };
        assert_ne!(bytes[0], FOUND_0X4A, "a different offset is a different question");

        // A digest the witness does not hold: still an answer, just not the found marker.
        let absent = ask(
            ScanParams::ModulePresence {
                seed: 1,
                name_digest: [0x11; 20],
            },
            CheckType::FindModuleByName,
            &witness,
        );
        let ScanOutcome::Answered(bytes) = absent else {
            panic!("must answer")
        };
        assert_ne!(bytes[0], FOUND_0X4A);

        // And the clock, reported as the witness saw it.
        let timing = ask(ScanParams::Timing, CheckType::CheckTimingValues, &witness);
        assert_eq!(
            timing,
            ScanOutcome::Answered(vec![1, 99, 0, 0, 0]),
            "mismatch byte then the tick count, little-endian"
        );
    }

    /// The image scans are unanswerable whatever the witness — this is a property, not a gap.
    #[test]
    fn the_image_scans_are_unanswerable_for_any_witness() {
        for check in [
            CheckType::ReadMemory,
            CheckType::FindCodeByHash,
            CheckType::FindMemImageCodeByHash,
        ] {
            match ask(ScanParams::Image, check, &TestWitness::default()) {
                ScanOutcome::Unanswerable(reason) => {
                    assert!(reason.contains("WoW.exe"), "{check:?}: {reason}")
                }
                ScanOutcome::Answered(b) => panic!("{check:?} answered {b:?}"),
            }
        }
    }

    /// Build a request the way `Warden::RequestScans` does — string table, scan block, terminator —
    /// walk it back, and check every decoded field. The module and API scans matter most here:
    /// their fields are a seed and digests that never appear in the string table.
    #[test]
    fn a_request_round_trips_into_a_checksummed_result() {
        let mut body = Vec::new();
        for s in [TOC, "UIParent", "Kernel32.dll", "GetTickCount"] {
            body.push(s.len() as u8);
            body.extend_from_slice(s.as_bytes());
        }
        body.push(0); // end of string table

        body.push(CheckType::HashClientFile as u8 ^ XOR);
        body.push(1);
        body.push(CheckType::GetLuaVariable as u8 ^ XOR);
        body.push(2);
        body.push(CheckType::FindModuleByName as u8 ^ XOR);
        body.extend_from_slice(&7u32.to_le_bytes());
        body.extend_from_slice(&[0xAB; 20]);
        body.push(CheckType::ApiCheck as u8 ^ XOR);
        body.extend_from_slice(&9u32.to_le_bytes());
        body.extend_from_slice(&[0xCD; 20]);
        body.push(3); // module index
        body.push(4); // proc index
        body.extend_from_slice(&16u32.to_le_bytes());
        body.push(8);
        body.push(CheckType::CheckTimingValues as u8 ^ XOR);
        body.push(TERMINATOR);

        let requests = parse_checks_request(&body, &decode, TERMINATOR).expect("parse");
        assert_eq!(requests.len(), 5, "every scan in the block must be walked");
        assert_eq!(
            requests[0].params,
            ScanParams::FileHash { path: TOC.into() }
        );
        assert_eq!(
            requests[1].params,
            ScanParams::LuaVariable { name: "UIParent".into() }
        );
        assert_eq!(
            requests[2].params,
            ScanParams::ModulePresence { seed: 7, name_digest: [0xAB; 20] },
            "the seed and digest are the only way to identify the module asked about"
        );
        assert_eq!(
            requests[3].params,
            ScanParams::ApiCheck {
                module: "Kernel32.dll".into(),
                proc: "GetTickCount".into(),
                hash: [0xCD; 20],
                offset: 16,
                length: 8,
            },
            "both string indices are 1-based and the module's comes first"
        );
        assert_eq!(requests[4].params, ScanParams::Timing);

        let outcomes: Vec<_> = requests.iter().map(|r| answer(r, &TestWitness::default())).collect();
        let packet = build_checks_result(&outcomes).expect("all witnessable");

        assert_eq!(packet[0], client_op::CHEAT_CHECKS_RESULT);
        let len = u16::from_le_bytes([packet[1], packet[2]]) as usize;
        let sum = u32::from_le_bytes([packet[3], packet[4], packet[5], packet[6]]);
        let payload = &packet[7..];
        assert_eq!(payload.len(), len, "declared length must match the payload");
        assert_eq!(
            sum,
            checks_result_checksum(payload),
            "the server recomputes this and kicks on a mismatch"
        );
        assert_eq!(
            payload.len(),
            21 + 7 + 1 + 1 + 5,
            "file hash + lua + module + api + timing, at their fixed widths"
        );
    }

    /// A memory scan in the set must stop the reply being built at all, carrying its reason out —
    /// never a filler byte, which the server would read as a positional answer to that scan.
    #[test]
    fn a_memory_scan_blocks_the_whole_reply() {
        let outcomes = vec![
            ScanOutcome::Answered(vec![0]),
            ask(ScanParams::Image, CheckType::ReadMemory, &TestWitness::default()),
        ];
        let err = build_checks_result(&outcomes).expect_err("must refuse");
        assert!(err.contains("WoW.exe"), "the reason must name why: {err}");
    }

    /// A memory scan's FIELDS are still consumed, so the scans after it in the same packet stay
    /// aligned — the block has no per-scan length, so skipping it by guesswork would corrupt them.
    #[test]
    fn a_memory_scan_is_walked_past_without_being_answered() {
        let mut body = vec![0u8]; // empty string table
        body.push(CheckType::ReadMemory as u8 ^ XOR);
        body.push(0); // no module string
        body.extend_from_slice(&0x0084_6be4u32.to_le_bytes());
        body.push(6);
        body.push(CheckType::CheckTimingValues as u8 ^ XOR);
        body.push(TERMINATOR);

        let requests = parse_checks_request(&body, &decode, TERMINATOR).expect("parse");
        assert_eq!(requests.len(), 2);
        assert_eq!(requests[0].params, ScanParams::Image);
        assert_eq!(
            requests[1].params,
            ScanParams::Timing,
            "the scan after a memory read must still decode"
        );
    }

    /// A type whose payload we have not read stops the walk instead of guessing its width.
    #[test]
    fn an_unmodelled_payload_stops_the_walk() {
        let body = vec![0u8, CheckType::FindCodeByHash as u8 ^ XOR, 0, 0, 0, 0];
        assert_eq!(
            parse_checks_request(&body, &decode, TERMINATOR),
            Err(RequestError::UnmodelledPayload(CheckType::FindCodeByHash))
        );
    }
}
