//! Warden anticheat — the client half of the `SMSG_WARDEN_DATA` / `CMSG_WARDEN_DATA` exchange.
//!
//! **Scope, stated up front because it bounds what this can ever do.** A Warden scan set is chosen
//! server-side per session and its checks are typed (`WardenScan.hpp`'s `WindowsScanType`). Of those
//! types, the ones this client can answer are the ones it can *witness about itself*:
//! `HASH_CLIENT_FILE` (it holds the real game files) and `GET_LUA_VARIABLE` (it holds a real Lua VM).
//! `READ_MEMORY`, `FIND_CODE_BY_HASH` and `FIND_MEM_IMAGE_CODE_BY_HASH` ask for bytes at addresses
//! inside `WoW.exe`; benilla is a from-scratch client and has no such image, so it cannot answer them
//! — and answering them from a copy of that binary would mean the check no longer says anything about
//! the client that is actually running. A server that wants to admit this client therefore needs a
//! scan profile made of the witnessable types; `WardenScanMgr::GetRandomScans` already selects by the
//! session's build flag, so that is a database question, not a protocol one.
//!
//! **The crypto is ported from the server it has to interoperate with**, not from memory:
//! `SHA1Randx` is a line-for-line port of tortoise-wow
//! `src/game/Anticheat/Warden/WardenKeyGeneration.h`, and the key direction is read off
//! `Warden.cpp`: the server inits `_inputCrypto` with the FIRST 16 generated bytes and decrypts
//! client→server traffic with it (`DecryptData`, `Warden.cpp:316-319`), and inits `_outputCrypto`
//! with the SECOND 16 for server→client (`EncryptData`, `:321-324`). Mirrored here, so this client
//! encrypts with key #1 and decrypts with key #2. Getting that pair backwards is the failure mode
//! this comment exists to prevent: it does not error, it just yields plausible-looking garbage.
//!
//! There is a second keying step: once a module is loaded the server re-inits both ciphers from the
//! module's own `clientKey`/`serverKey` (`Warden.cpp:141-142`). [`WardenCrypto::rekey`] is that step.

use sha1::{Digest, Sha1};

/// `SHA1Randx` — the server's key-stream generator over the session key
/// (`WardenKeyGeneration.h`). Hash the first half into `o1` and the second into `o2`, then emit
/// 20-byte blocks of `SHA1(o1 ‖ o0 ‖ o2)`, feeding each block back in as the next `o0`.
struct Sha1Randx {
    o0: [u8; 20],
    o1: [u8; 20],
    o2: [u8; 20],
    taken: usize,
}

impl Sha1Randx {
    fn new(seed: &[u8]) -> Self {
        let half = seed.len() / 2;
        let o1: [u8; 20] = Sha1::digest(&seed[..half]).into();
        let o2: [u8; 20] = Sha1::digest(&seed[half..]).into();
        let mut s = Sha1Randx {
            o0: [0u8; 20],
            o1,
            o2,
            taken: 0,
        };
        s.fill_up();
        s
    }

    fn fill_up(&mut self) {
        let mut sha = Sha1::new();
        sha.update(self.o1);
        sha.update(self.o0);
        sha.update(self.o2);
        self.o0 = sha.finalize().into();
        self.taken = 0;
    }

    /// The server's `Generate`: refill only when the current block is spent, then take one byte.
    fn generate(&mut self, out: &mut [u8]) {
        for byte in out.iter_mut() {
            if self.taken == 20 {
                self.fill_up();
            }
            *byte = self.o0[self.taken];
            self.taken += 1;
        }
    }
}

/// RC4/ARC4 — the stream cipher both Warden directions run on (`Auth/ARC4`). Stateful: each call
/// continues the keystream, so one instance belongs to exactly one direction of one session.
pub struct Rc4 {
    s: [u8; 256],
    i: u8,
    j: u8,
}

impl Rc4 {
    pub fn new(key: &[u8]) -> Self {
        let mut s = [0u8; 256];
        for (i, v) in s.iter_mut().enumerate() {
            *v = i as u8;
        }
        let mut j = 0u8;
        for i in 0..256 {
            j = j
                .wrapping_add(s[i])
                .wrapping_add(key[i % key.len()]);
            s.swap(i, j as usize);
        }
        Rc4 { s, i: 0, j: 0 }
    }

    /// XOR `buf` with the next keystream bytes, in place. RC4 is symmetric — the same call both
    /// encrypts and decrypts.
    pub fn apply(&mut self, buf: &mut [u8]) {
        for byte in buf.iter_mut() {
            self.i = self.i.wrapping_add(1);
            self.j = self.j.wrapping_add(self.s[self.i as usize]);
            self.s.swap(self.i as usize, self.j as usize);
            let k = self.s[self.i as usize].wrapping_add(self.s[self.j as usize]);
            *byte ^= self.s[k as usize];
        }
    }
}

/// The bytes generated per direction (`Warden::Warden`'s `KeyLength`).
const KEY_LENGTH: usize = 16;

/// Both directions of one Warden session.
pub struct WardenCrypto {
    /// Applied to what we SEND — the server decrypts it with its `_inputCrypto`.
    outgoing: Rc4,
    /// Applied to what we RECEIVE — the server encrypted it with its `_outputCrypto`.
    incoming: Rc4,
}

impl WardenCrypto {
    /// Derive both ciphers from the SRP6 session key, exactly as `Warden::Warden` does.
    pub fn from_session_key(session_key: &[u8]) -> Self {
        let mut rand = Sha1Randx::new(session_key);
        let mut first = [0u8; KEY_LENGTH];
        let mut second = [0u8; KEY_LENGTH];
        rand.generate(&mut first);
        rand.generate(&mut second);
        WardenCrypto {
            outgoing: Rc4::new(&first),
            incoming: Rc4::new(&second),
        }
    }

    /// Re-key from a loaded module's own pair (`Warden.cpp:141-142`). `client_key` is the one the
    /// server will decrypt our traffic with, so it is ours to encrypt with.
    pub fn rekey(&mut self, client_key: &[u8], server_key: &[u8]) {
        self.outgoing = Rc4::new(client_key);
        self.incoming = Rc4::new(server_key);
    }

    pub fn decrypt(&mut self, buf: &mut [u8]) {
        self.incoming.apply(buf);
    }

    pub fn encrypt(&mut self, buf: &mut [u8]) {
        self.outgoing.apply(buf);
    }
}

/// Server→client Warden opcodes — the first byte of a decrypted `SMSG_WARDEN_DATA` body.
///
/// Their numbering is the oracle for whether [`WardenCrypto`] is keyed correctly: a correct decrypt
/// puts a value in `0..=4` here, a swapped key pair puts noise. That is the check to run first
/// against a live server, since no fixture can stand in for the server's own keystream.
pub mod server_op {
    pub const MODULE_USE: u8 = 0x00;
    pub const MODULE_CACHE: u8 = 0x01;
    pub const CHEAT_CHECKS_REQUEST: u8 = 0x02;
    pub const MODULE_INITIALIZE: u8 = 0x03;
    pub const MEM_CHECKS_REQUEST: u8 = 0x04;
    pub const HASH_REQUEST: u8 = 0x05;
}

/// Client→server Warden opcodes — the first byte of a `CMSG_WARDEN_DATA` body we send.
pub mod client_op {
    pub const MODULE_MISSING: u8 = 0x00;
    pub const MODULE_OK: u8 = 0x01;
    pub const CHEAT_CHECKS_RESULT: u8 = 0x02;
    pub const MEM_CHECKS_RESULT: u8 = 0x03;
    pub const HASH_RESULT: u8 = 0x04;
    pub const MODULE_FAILED: u8 = 0x05;
}

/// A decrypted server message, far enough parsed to say what it wants.
#[derive(Debug)]
pub enum ServerMessage {
    /// Load this module: 16-byte id, 16-byte key, and its compressed size.
    ModuleUse {
        id: [u8; 16],
        key: [u8; 16],
        size: u32,
    },
    /// One chunk of the module transfer.
    ModuleCache { chunk: Vec<u8> },
    /// The module is in place; the checks follow.
    ModuleInitialize,
    /// A scan request. The body is the module's own encoding, so it is carried raw until the
    /// module's check layout is implemented.
    CheatChecksRequest { body: Vec<u8> },
    /// Prove which module we hold.
    HashRequest { seed: Vec<u8> },
    /// An opcode this client does not model — carried whole so a caller can log it rather than
    /// guess. A value outside `server_op` here almost always means the keys are wrong, not that the
    /// server invented an opcode.
    Unknown { opcode: u8, body: Vec<u8> },
}

/// Parse one **already decrypted** `SMSG_WARDEN_DATA` body.
pub fn parse_server_message(body: &[u8]) -> Option<ServerMessage> {
    let (&opcode, rest) = body.split_first()?;
    Some(match opcode {
        server_op::MODULE_USE if rest.len() >= 36 => {
            let mut id = [0u8; 16];
            let mut key = [0u8; 16];
            id.copy_from_slice(&rest[..16]);
            key.copy_from_slice(&rest[16..32]);
            ServerMessage::ModuleUse {
                id,
                key,
                size: u32::from_le_bytes([rest[32], rest[33], rest[34], rest[35]]),
            }
        }
        server_op::MODULE_CACHE => ServerMessage::ModuleCache {
            chunk: rest.to_vec(),
        },
        server_op::MODULE_INITIALIZE => ServerMessage::ModuleInitialize,
        server_op::CHEAT_CHECKS_REQUEST => ServerMessage::CheatChecksRequest {
            body: rest.to_vec(),
        },
        server_op::HASH_REQUEST => ServerMessage::HashRequest {
            seed: rest.to_vec(),
        },
        other => ServerMessage::Unknown {
            opcode: other,
            body: rest.to_vec(),
        },
    })
}

// --- the scan lane -------------------------------------------------------------------------------
//
// Everything above is the transport. What follows is what a scan request MEANS, and it is written
// against a contract this client cannot read off the wire on its own: the byte that names a check's
// type is `module->opcodes[type] ^ xor` (`WardenScan.cpp`'s builders), and that table lives inside
// the module. A client that does not execute the module therefore cannot dispatch a request built
// the stock way — so this lane is written for a server profile that fixes the encoding instead, and
// [`CheckType`] is the mapping it proposes.

/// The scan types, numbered as `WindowsScanType` numbers them (`WardenScan.hpp:42-53`). The wire
/// byte is NOT this value on a stock server — see the note above — but the enum is the server's, so
/// a fixed-encoding profile has an obvious mapping to adopt.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckType {
    ReadMemory = 0,
    FindModuleByName = 1,
    FindMemImageCodeByHash = 2,
    FindCodeByHash = 3,
    HashClientFile = 4,
    GetLuaVariable = 5,
    ApiCheck = 6,
    FindDriverByName = 7,
    CheckTimingValues = 8,
}

impl CheckType {
    pub fn from_u8(v: u8) -> Option<Self> {
        Some(match v {
            0 => CheckType::ReadMemory,
            1 => CheckType::FindModuleByName,
            2 => CheckType::FindMemImageCodeByHash,
            3 => CheckType::FindCodeByHash,
            4 => CheckType::HashClientFile,
            5 => CheckType::GetLuaVariable,
            6 => CheckType::ApiCheck,
            7 => CheckType::FindDriverByName,
            8 => CheckType::CheckTimingValues,
            _ => return None,
        })
    }

    /// Can this client witness the answer *about itself*?
    ///
    /// The three `false` rows are not unimplemented work — they are questions about the contents of
    /// a `WoW.exe` process image, asked of a client that is not one. There is no state in this
    /// program that constitutes an answer, so the only way to produce one is to copy it from
    /// somewhere else, and a copied answer says nothing about the client that sent it. They are
    /// therefore permanently [`ScanOutcome::Unanswerable`], and a profile that includes them is
    /// asking for an answer that could not mean anything.
    pub fn is_witnessable(self) -> bool {
        match self {
            // Reads of a PE image this client does not have.
            CheckType::ReadMemory | CheckType::FindMemImageCodeByHash | CheckType::FindCodeByHash => {
                false
            }
            // Real files we hold, and our own Lua VM: these say something about us.
            CheckType::HashClientFile | CheckType::GetLuaVariable => true,
            // Process/driver/API surfaces a browser sandbox does not have. Answerable truthfully —
            // the honest answer is always "absent" — but that makes them free to pass and therefore
            // worth nothing as checks. Reported so a profile author can see they are noise.
            CheckType::FindModuleByName | CheckType::FindDriverByName | CheckType::ApiCheck => true,
            CheckType::CheckTimingValues => true,
        }
    }
}

/// What answering one check produced.
#[derive(Debug, PartialEq, Eq)]
pub enum ScanOutcome {
    /// The bytes to put in `CHEAT_CHECKS_RESULT` for this check, in request order.
    Answered(Vec<u8>),
    /// No answer exists for this client. Carries the reason so it reaches a log rather than
    /// becoming a silent zero — a silent wrong answer is indistinguishable from a cheat.
    Unanswerable(&'static str),
}

/// What a check asked for, decoded under a fixed-encoding profile.
#[derive(Debug, PartialEq, Eq)]
pub struct ScanRequest {
    pub check: CheckType,
    /// The check's string parameter: a file path for `HashClientFile`, a global's name for
    /// `GetLuaVariable`, a module/driver name for the lookups.
    pub param: String,
}

/// What one attestation produced.
///
/// `Absent` and `NotImplemented` are kept apart on purpose, and the distinction is the whole point
/// of this type: "there is no such file" is an ANSWER the client witnessed, while "we never wrote
/// the file-hashing path" is a GAP. Collapsing them would make every unimplemented check report a
/// clean result — a silent no-op that reads as a pass, which is the one failure mode this lane must
/// not have.
#[derive(Debug, PartialEq, Eq)]
pub enum Attestation<T> {
    /// The client looked and found it.
    Present(T),
    /// The client looked and it is genuinely not there.
    Absent,
    /// The client cannot say. Never becomes an answer; it becomes an
    /// [`ScanOutcome::Unanswerable`] that names itself.
    NotImplemented,
}

/// What the client can consult to answer a check about itself.
///
/// One method per witnessable scan type, every one defaulting to
/// [`Attestation::NotImplemented`] so an implementor adds them at their own pace and an unwritten
/// one is NAMED rather than silently passing. There is deliberately no method for `READ_MEMORY`,
/// `FIND_CODE_BY_HASH` or `FIND_MEM_IMAGE_CODE_BY_HASH`: those ask for the contents of a `WoW.exe`
/// process image, and no implementation of this trait can witness one, so a stub for them would be
/// a slot for a value copied from elsewhere rather than a gap waiting to be filled. They are
/// answered as permanently unanswerable in [`answer`], with the reason attached.
pub trait ScanWitness {
    /// SHA-1 of the named client file as this client actually holds it. Hash what was DOWNLOADED,
    /// not what a host says it served — the answer has to be a fact about this client.
    fn hash_client_file(&self, _path: &str) -> Attestation<[u8; 20]> {
        Attestation::NotImplemented
    }

    /// The value of a Lua global in this client's own VM.
    fn lua_variable(&self, _name: &str) -> Attestation<String> {
        Attestation::NotImplemented
    }

    /// Is a module of this name loaded in the client's process?
    ///
    /// A browser has no process modules, so a web client's honest answer is always `Absent` — which
    /// makes this check free to pass and therefore worth nothing as a check. Left implementable
    /// rather than hard-wired, because a native build of this client could answer it meaningfully.
    fn module_loaded(&self, _name: &str) -> Attestation<()> {
        Attestation::NotImplemented
    }

    /// Is a driver of this name present? Same standing as [`Self::module_loaded`].
    fn driver_loaded(&self, _name: &str) -> Attestation<()> {
        Attestation::NotImplemented
    }

    /// Has the named API entry point been detoured? `Absent` means "not detoured".
    fn api_detoured(&self, _name: &str) -> Attestation<()> {
        Attestation::NotImplemented
    }

    /// The client's timing values, in the shape the profile asks for.
    fn timing_values(&self) -> Attestation<Vec<u8>> {
        Attestation::NotImplemented
    }
}

/// The found/not-found byte both witnessable scans lead with: the server's checkers read `0` as
/// found (`WindowsFileHashScan`/`WindowsLuaScan`: `auto const found = !buff.read<uint8>()`).
const FOUND: u8 = 0;
const NOT_FOUND: u8 = 1;

/// A presence-only answer, for the scans whose reply is just the found byte.
fn presence(attestation: Attestation<()>, gap: &'static str) -> ScanOutcome {
    match attestation {
        Attestation::Present(()) => ScanOutcome::Answered(vec![FOUND]),
        Attestation::Absent => ScanOutcome::Answered(vec![NOT_FOUND]),
        Attestation::NotImplemented => ScanOutcome::Unanswerable(gap),
    }
}

/// Answer one check. Gaps and structural impossibilities are both named, never faked.
pub fn answer(request: &ScanRequest, witness: &dyn ScanWitness) -> ScanOutcome {
    match request.check {
        CheckType::ReadMemory => ScanOutcome::Unanswerable(
            "READ_MEMORY reads a WoW.exe process image; this client has none",
        ),
        CheckType::FindMemImageCodeByHash | CheckType::FindCodeByHash => ScanOutcome::Unanswerable(
            "code-by-hash scans search a WoW.exe image; this client has none",
        ),
        CheckType::HashClientFile => match witness.hash_client_file(&request.param) {
            Attestation::Present(hash) => {
                let mut out = Vec::with_capacity(1 + hash.len());
                out.push(FOUND);
                out.extend_from_slice(&hash);
                ScanOutcome::Answered(out)
            }
            Attestation::Absent => ScanOutcome::Answered(vec![NOT_FOUND]),
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::hash_client_file is not implemented")
            }
        },
        CheckType::GetLuaVariable => match witness.lua_variable(&request.param) {
            Attestation::Present(value) => {
                let len = value.len().min(u8::MAX as usize);
                let mut out = Vec::with_capacity(2 + len);
                out.push(FOUND);
                out.push(len as u8);
                out.extend_from_slice(&value.as_bytes()[..len]);
                ScanOutcome::Answered(out)
            }
            Attestation::Absent => ScanOutcome::Answered(vec![NOT_FOUND]),
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::lua_variable is not implemented")
            }
        },
        CheckType::FindModuleByName => presence(
            witness.module_loaded(&request.param),
            "ScanWitness::module_loaded is not implemented",
        ),
        CheckType::FindDriverByName => presence(
            witness.driver_loaded(&request.param),
            "ScanWitness::driver_loaded is not implemented",
        ),
        CheckType::ApiCheck => presence(
            witness.api_detoured(&request.param),
            "ScanWitness::api_detoured is not implemented",
        ),
        CheckType::CheckTimingValues => match witness.timing_values() {
            Attestation::Present(bytes) => ScanOutcome::Answered(bytes),
            Attestation::Absent => ScanOutcome::Answered(vec![NOT_FOUND]),
            Attestation::NotImplemented => {
                ScanOutcome::Unanswerable("ScanWitness::timing_values is not implemented")
            }
        },
    }
}

// --- request framing -----------------------------------------------------------------------------
//
// `Warden::RequestScans` (`Warden.cpp:246-274`) assembles a Windows request as:
//
//     u8  CHEAT_CHECKS_REQUEST
//     string table: repeated { u8 len, bytes[len] }, terminated by a single u8 0
//     the scan block: each scan's own bytes, back to back
//     u8  module->scanTerminator ^ xor
//
// and each scan begins with `module->opcodes[type] ^ xor`. Both bytes come from the module, which is
// why `decode_type` and `terminator` are parameters here rather than constants: a profile that fixes
// the encoding supplies them, and nothing in this file has to guess.
//
// The two witnessable scans share one payload: `u8 string_index`, 1-based because the server takes
// `strings.size()` AFTER pushing (`WardenScan.cpp:214-219` and `:254-259`). Layouts for the other
// types are deliberately not modelled — we have not read them, and inventing one would desync the
// walk rather than fail it.

/// Why a request could not be read. A parse that stops is worth more than one that guesses: the
/// scan block has no per-scan length, so a wrong payload width silently turns the rest of the
/// packet into nonsense.
#[derive(Debug, PartialEq, Eq)]
pub enum RequestError {
    Truncated(&'static str),
    /// A type byte `decode_type` did not recognise.
    UnknownType(u8),
    /// A type we can recognise but whose payload layout this client has not modelled, so the walk
    /// cannot continue past it.
    UnmodelledPayload(CheckType),
    /// A scan referenced a string index the table does not have.
    BadStringIndex(u8),
}

/// Parse a decrypted `CHEAT_CHECKS_REQUEST` body (opcode byte already stripped).
pub fn parse_checks_request(
    body: &[u8],
    decode_type: &dyn Fn(u8) -> Option<CheckType>,
    terminator: u8,
) -> Result<Vec<ScanRequest>, RequestError> {
    let mut at = 0usize;
    let mut strings: Vec<String> = Vec::new();
    loop {
        let len = *body.get(at).ok_or(RequestError::Truncated("string table"))? as usize;
        at += 1;
        if len == 0 {
            break;
        }
        let end = at + len;
        let raw = body.get(at..end).ok_or(RequestError::Truncated("string"))?;
        strings.push(String::from_utf8_lossy(raw).into_owned());
        at = end;
    }

    let mut out = Vec::new();
    loop {
        let byte = *body.get(at).ok_or(RequestError::Truncated("scan block"))?;
        at += 1;
        if byte == terminator {
            return Ok(out);
        }
        let check = decode_type(byte).ok_or(RequestError::UnknownType(byte))?;
        match check {
            CheckType::HashClientFile | CheckType::GetLuaVariable => {
                let index = *body.get(at).ok_or(RequestError::Truncated("string index"))?;
                at += 1;
                let param = strings
                    .get((index as usize).wrapping_sub(1))
                    .ok_or(RequestError::BadStringIndex(index))?
                    .clone();
                out.push(ScanRequest { check, param });
            }
            other => return Err(RequestError::UnmodelledPayload(other)),
        }
    }
}

/// The server's `BuildChecksum` (`Warden.cpp:351-362`): SHA-1 over the result payload, then the five
/// 32-bit words of the digest XORed together, little-endian.
pub fn checks_result_checksum(payload: &[u8]) -> u32 {
    let hash: [u8; 20] = Sha1::digest(payload).into();
    let mut sum = 0u32;
    for word in hash.chunks_exact(4) {
        sum ^= u32::from_le_bytes([word[0], word[1], word[2], word[3]]);
    }
    sum
}

/// Assemble `CHEAT_CHECKS_RESULT`: `u8 opcode, u16 length, u32 checksum, payload`, the order the
/// server reads it in (`Warden.cpp:425-429`).
///
/// Refuses to build when any outcome is [`ScanOutcome::Unanswerable`], carrying that reason out.
/// There is no filler byte that would be honest here — the server matches results to the scans it
/// sent, positionally, so a placeholder is not a gap in the reply, it is a false answer to a
/// specific question.
pub fn build_checks_result(outcomes: &[ScanOutcome]) -> Result<Vec<u8>, &'static str> {
    let mut payload = Vec::new();
    for outcome in outcomes {
        match outcome {
            ScanOutcome::Answered(bytes) => payload.extend_from_slice(bytes),
            ScanOutcome::Unanswerable(reason) => return Err(reason),
        }
    }
    let mut packet = Vec::with_capacity(1 + 2 + 4 + payload.len());
    packet.push(client_op::CHEAT_CHECKS_RESULT);
    packet.extend_from_slice(&(payload.len() as u16).to_le_bytes());
    packet.extend_from_slice(&checks_result_checksum(&payload).to_le_bytes());
    packet.extend_from_slice(&payload);
    Ok(packet)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A witness standing in for a fully implemented client: it holds one game file, one Lua
    /// global, and can speak to the browser-shaped surfaces (all absent).
    struct TestWitness;

    impl ScanWitness for TestWitness {
        fn hash_client_file(&self, path: &str) -> Attestation<[u8; 20]> {
            if path == r"Interface\FrameXML\FrameXML.toc" {
                Attestation::Present(Sha1::digest(b"toc").into())
            } else {
                Attestation::Absent
            }
        }
        fn lua_variable(&self, name: &str) -> Attestation<String> {
            if name == "UIParent" {
                Attestation::Present("table".to_string())
            } else {
                Attestation::Absent
            }
        }
        fn module_loaded(&self, _name: &str) -> Attestation<()> {
            Attestation::Absent
        }
        fn driver_loaded(&self, _name: &str) -> Attestation<()> {
            Attestation::Absent
        }
        fn api_detoured(&self, _name: &str) -> Attestation<()> {
            Attestation::Absent
        }
        fn timing_values(&self) -> Attestation<Vec<u8>> {
            Attestation::Present(vec![0])
        }
    }

    /// The default trait bodies: a client that has implemented nothing must produce NAMED gaps, not
    /// clean passes. This is the regression that matters most in this file — a silent `Answered`
    /// here would mean every unimplemented check reports "nothing wrong".
    struct EmptyWitness;
    impl ScanWitness for EmptyWitness {}

    #[test]
    fn an_unimplemented_witness_names_its_gaps_instead_of_passing() {
        for check in [
            CheckType::HashClientFile,
            CheckType::GetLuaVariable,
            CheckType::FindModuleByName,
            CheckType::FindDriverByName,
            CheckType::ApiCheck,
            CheckType::CheckTimingValues,
        ] {
            let outcome = answer(
                &ScanRequest {
                    check,
                    param: "x".into(),
                },
                &EmptyWitness,
            );
            match outcome {
                ScanOutcome::Unanswerable(reason) => assert!(
                    reason.contains("not implemented"),
                    "{check:?} gap must name itself: {reason}"
                ),
                ScanOutcome::Answered(bytes) => {
                    panic!("{check:?} answered {bytes:?} with nothing implemented")
                }
            }
        }
    }

    /// A profile's fixed encoding, standing in for the module's `opcodes[]` table: here the wire
    /// byte is the scan type plus an offset, xored, so the test exercises a real indirection rather
    /// than an identity mapping that would hide an index bug.
    const XOR: u8 = 0x5a;
    const TERMINATOR: u8 = 0xff ^ XOR;

    fn decode(byte: u8) -> Option<CheckType> {
        CheckType::from_u8(byte ^ XOR)
    }

    /// Build a request the way `Warden::RequestScans` does, walk it back, answer it, and assemble
    /// the reply — the whole lane, end to end, without a server.
    #[test]
    fn a_request_round_trips_into_a_checksummed_result() {
        let mut body = Vec::new();
        for s in [r"Interface\FrameXML\FrameXML.toc", "UIParent"] {
            body.push(s.len() as u8);
            body.extend_from_slice(s.as_bytes());
        }
        body.push(0); // end of string table
        body.push(CheckType::HashClientFile as u8 ^ XOR);
        body.push(1); // 1-based index into the table
        body.push(CheckType::GetLuaVariable as u8 ^ XOR);
        body.push(2);
        body.push(TERMINATOR);

        let requests = parse_checks_request(&body, &decode, TERMINATOR).expect("parse");
        assert_eq!(requests.len(), 2);
        assert_eq!(requests[0].check, CheckType::HashClientFile);
        assert_eq!(requests[0].param, r"Interface\FrameXML\FrameXML.toc");
        assert_eq!(requests[1].check, CheckType::GetLuaVariable);
        assert_eq!(requests[1].param, "UIParent");

        let outcomes: Vec<_> = requests
            .iter()
            .map(|r| answer(r, &TestWitness))
            .collect();
        let packet = build_checks_result(&outcomes).expect("both are witnessable");

        assert_eq!(packet[0], client_op::CHEAT_CHECKS_RESULT);
        let len = u16::from_le_bytes([packet[1], packet[2]]) as usize;
        let sum = u32::from_le_bytes([packet[3], packet[4], packet[5], packet[6]]);
        let payload = &packet[7..];
        assert_eq!(payload.len(), len, "declared length must match the payload");
        assert_eq!(sum, checks_result_checksum(payload), "server recomputes this and kicks on a mismatch");
    }

    /// A memory scan in the set must stop the reply being built at all, carrying its reason out —
    /// never a filler byte, which the server would read as a positional answer to that scan.
    #[test]
    fn a_memory_scan_blocks_the_whole_reply() {
        let outcomes = vec![
            ScanOutcome::Answered(vec![0]),
            answer(
                &ScanRequest {
                    check: CheckType::ReadMemory,
                    param: String::new(),
                },
                &TestWitness,
            ),
        ];
        let err = build_checks_result(&outcomes).expect_err("must refuse");
        assert!(err.contains("WoW.exe"), "the reason must name why: {err}");
    }

    /// A type we recognise but whose payload we have not modelled stops the walk instead of
    /// guessing its width — the scan block has no per-scan length, so a wrong guess turns the rest
    /// of the packet into nonsense rather than into an error.
    #[test]
    fn an_unmodelled_payload_stops_the_walk() {
        let body = vec![0u8, CheckType::ReadMemory as u8 ^ XOR, 0, 0, 0, 0];
        assert_eq!(
            parse_checks_request(&body, &decode, TERMINATOR),
            Err(RequestError::UnmodelledPayload(CheckType::ReadMemory))
        );
    }

    /// Every scan type, answered. The three memory types must come back `Unanswerable` and the rest
    /// must produce bytes — this is the line the whole lane is built around, and a change that lets
    /// a memory scan return `Answered` has broken it.
    #[test]
    fn memory_scans_are_unanswerable_and_the_rest_are_witnessed() {
        let all = [
            CheckType::ReadMemory,
            CheckType::FindModuleByName,
            CheckType::FindMemImageCodeByHash,
            CheckType::FindCodeByHash,
            CheckType::HashClientFile,
            CheckType::GetLuaVariable,
            CheckType::ApiCheck,
            CheckType::FindDriverByName,
            CheckType::CheckTimingValues,
        ];
        let mut unanswerable = Vec::new();
        for check in all {
            let param = match check {
                CheckType::HashClientFile => r"Interface\FrameXML\FrameXML.toc",
                CheckType::GetLuaVariable => "UIParent",
                _ => "Cheat Engine",
            }
            .to_string();
            let outcome = answer(&ScanRequest { check, param }, &TestWitness);
            match outcome {
                ScanOutcome::Unanswerable(reason) => {
                    assert!(!check.is_witnessable(), "{check:?} claims to be witnessable");
                    unanswerable.push((check, reason));
                }
                ScanOutcome::Answered(bytes) => {
                    assert!(check.is_witnessable(), "{check:?} answered but is not witnessable");
                    assert!(!bytes.is_empty(), "{check:?} answered with nothing");
                }
            }
        }
        let failed: Vec<_> = unanswerable.iter().map(|(c, _)| *c).collect();
        assert_eq!(
            failed,
            vec![
                CheckType::ReadMemory,
                CheckType::FindMemImageCodeByHash,
                CheckType::FindCodeByHash
            ],
            "exactly the WoW.exe-image scans must fail, no more and no fewer"
        );
    }

    /// A file the client does not hold answers "not found" rather than inventing a digest, and one
    /// it does hold answers with its real SHA-1 — the found/not-found byte is 0 for found, matching
    /// `WindowsFileHashScan`'s checker.
    #[test]
    fn a_file_hash_answers_from_what_the_client_actually_holds() {
        let held = answer(
            &ScanRequest {
                check: CheckType::HashClientFile,
                param: r"Interface\FrameXML\FrameXML.toc".into(),
            },
            &TestWitness,
        );
        let expected: [u8; 20] = Sha1::digest(b"toc").into();
        let mut want = vec![FOUND];
        want.extend_from_slice(&expected);
        assert_eq!(held, ScanOutcome::Answered(want));

        let absent = answer(
            &ScanRequest {
                check: CheckType::HashClientFile,
                param: r"Interface\NotHere.blp".into(),
            },
            &TestWitness,
        );
        assert_eq!(absent, ScanOutcome::Answered(vec![NOT_FOUND]));
    }
}
